# Generated by Django 3.0.2 on 2020-06-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpost', '0004_auto_20200603_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='postdata',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
